[features]
seeds = false
skip-lint = false
[programs.devnet]
myepicproject = "2b38tdiwrLj5hpn54GYij8iLVZ1VWjc43RMmFRaRYJo1"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/ibmeshach/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"

[test]
startup_wait = 100000